#!/bin/bash
# Unit-level harness for test/gha-e2e/mooncake/image/custom-entrypoint.sh
# (worker role). Feeds it the real runtime.json produced by the controller's
# generateRuntimeConfigData for the mooncake manifests (generated by
# pkg/ddc/cache/engine/verify_p0_clientless_test.go into fixtures/runtime.json)
# and stubs mooncake_client to capture the arguments it would be exec'd with.
set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VERIFY_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../../.." && pwd)"
ENTRYPOINT="$REPO_ROOT/test/gha-e2e/mooncake/image/custom-entrypoint.sh"
FIXTURE="$VERIFY_DIR/fixtures/runtime.json"

[[ -f "$FIXTURE" ]] || { echo "FAIL: fixture $FIXTURE missing; run the P0 Go test with VERIFY_RUNTIME_JSON_OUT first"; exit 1; }

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT
mkdir -p "$TMP/bin"

cat > "$TMP/bin/mooncake_client" <<'STUB'
#!/bin/bash
echo "MOONCAKE_CLIENT_INVOKED"
for a in "$@"; do echo "ARG: $a"; done
STUB
chmod +x "$TMP/bin/mooncake_client"

failures=0
expect_arg() {
    local want="$1"
    if grep -qx "ARG: $want" "$TMP/out"; then
        echo "PASS: worker invoked with $want"
    else
        echo "FAIL: worker missing arg $want"
        failures=$((failures + 1))
    fi
}

FLUID_RUNTIME_CONFIG_PATH="$FIXTURE" FLUID_DATASET_NAMESPACE="default" POD_NAME="mooncake-demo-worker-0" \
    PATH="$TMP/bin:$PATH" bash "$ENTRYPOINT" worker start > "$TMP/out" 2>&1
rc=$?
if [[ $rc -ne 0 ]]; then
    echo "FAIL: entrypoint exited rc=$rc:"; cat "$TMP/out"
    exit 1
fi
grep -q "MOONCAKE_CLIENT_INVOKED" "$TMP/out" || { echo "FAIL: mooncake_client never invoked:"; cat "$TMP/out"; exit 1; }

expect_arg "--host=mooncake-demo-worker-0.svc-mooncake-demo-worker.default.svc.cluster.local"
expect_arg "--master_server_address=svc-mooncake-demo-master.default.svc.cluster.local:50051"
expect_arg "--metadata_server=http://svc-mooncake-demo-master.default.svc.cluster.local:8080/metadata"
# quota "1Gi" from the CacheRuntime tieredStore must reach mooncake as "1GB"
expect_arg "--global_segment_size=1GB"

# client role must fail loudly for this client-less runtime
FLUID_RUNTIME_CONFIG_PATH="$FIXTURE" PATH="$TMP/bin:$PATH" bash "$ENTRYPOINT" client start >/dev/null 2>&1
if [[ $? -ne 0 ]]; then
    echo "PASS: client role exits non-zero (client-less system)"
else
    echo "FAIL: client role exited 0"
    failures=$((failures + 1))
fi

if [[ $failures -gt 0 ]]; then
    echo "entrypoint harness: $failures failure(s)"
    exit 1
fi
echo "entrypoint harness: all cases passed"
